### PR TITLE
fix: (farms) Missing validations and add numeric keyboard support for mobile

### LINKED ISSUE #864: Unstake confirm button is active when empty input
Screenshot 2021-04-13 at 10 21 17

### LINKED ISSUE #865: Unstake confirm button when input exceeds max value
Screenshot 2021-04-13 at 10 21 40

### LINKED ISSUE #866: Unstake input accepts number with letters
Screenshot 2021-04-13 at 10 22 07

### LINKED ISSUE #867: Unstake and stake modal doesn't have numeric keyboard support for mobile
WhatsApp Image 2021-04-13 at 10 27 33

### PR DESCRIPTION
**Pull request by memoyil**
Fixes #864, fixes #865, fixes #866, fixes #867

### CODE REVIEW

File: src/views/Farms/components/DepositModal.tsx [hunk 1]
```diff
@@ -50,7 +52,12 @@ const DepositModal: React.FC<DepositModalProps> = ({ max, onConfirm, onDismiss,
         </Button>
         <Button
           width="100%"
-          disabled={pendingTx || fullBalance === '0' || val === '0'}
+          disabled={
+            pendingTx ||
+            parseFloat(fullBalance) === 0 ||
```
Comment (RabbitDoge) [inline src/views/Farms/components/DepositModal.tsx:57]: Why don't you create 2 variables `BigNumber` instead of mixing parseFloat, Number, and BigNumber ?

Comment (memoyil) [reply src/views/Farms/components/DepositModal.tsx]: Done

**Comment by memoyil** [comment]
@RabbitDoge Decided to remove input type number and replace comma (even if it shows value with comma it uses with dot underneath) with dot always also visually otherwise that might be confusing for the users that see, particularly in ios numeric keyboard, comma value but balance input with dot value.

Before:

image

After:

image

**Review by hachiojidev — APPROVED** [review]
