### PR TITLE
fix: Sort field not updated when using table sort function

### LINKED ISSUE #4604: [BUG] Sort field not updated when using table sort function
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

NFT

### Current Behavior

No updating on "SORT BY" field.
See details #4603 

### Expected Behavior

"SORT BY" field should be changed.

### Steps To Reproduce

1. Go to [Collections ](https://pancakeswap.finance/nfts/collections)Page
2. Sort table by selecting the table header

### Environment

```markdown
- Device:
- OS:
- Browser:
- Wallet:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by stvegerrad**
image
Table was sorted by Volume but "SORT BY" field still shows Collection.
Fixes #4604

### CODE REVIEW

File: src/components/Select/Select.tsx [hunk 1]
```diff
@@ -141,6 +141,10 @@ const Select: React.FunctionComponent<React.PropsWithChildren<SelectProps>> = ({
     }
   }, [])
 
+  useEffect(() => {
+    setSelectedOptionIndex(defaultOptionIndex)
+  }, [defaultOptionIndex])
+
```
Comment (chef-jojo) [inline src/components/Select/Select.tsx:147]: not a fan of using `defaultOptionIndex` as `value`. but it's a flawed design on this Select component.
I will let this pass this time

**Comment by chef-jojo** [comment]
LGTM, let's add the changes as @memoyil suggested

**Comment by stvegerrad** [comment]
> LGTM, let's add the changes as @memoyil suggested

Okay, I'll do it

**Comment by stvegerrad** [comment]
@memoyil @chef-jojo I just made changes, please check them and let me know

File: src/views/Nft/market/Collections/index.tsx [hunk 2]
```diff
@@ -79,6 +79,44 @@ const Collectible = () => {
...
+      {
+        label: t('Lowest Price'),
+        value: SORT_FIELD.lowestPrice,
+      },
+      {
+        label: t('Highest Price'),
+        value: SORT_FIELD.highestPrice,
+      },
+    ]
+  }, []);
```
Comment (chef-jojo) [inline src/views/Nft/market/Collections/index.tsx:109]: Missing deps

Comment (stvegerrad) [reply src/views/Nft/market/Collections/index.tsx]: I just added it, please check again

File: src/components/Select/Select.tsx [hunk 3]
```diff
@@ -141,6 +141,13 @@ const Select: React.FunctionComponent<React.PropsWithChildren<SelectProps>> = ({
     }
   }, [])
 
+  useEffect(() => {
+    if(defaultOptionIndex) {
+      setSelectedOptionIndex(defaultOptionIndex - 1)
```
Comment (chef-jojo) [inline src/components/Select/Select.tsx:146]: start index by 0

File: src/components/Select/Select.tsx [hunk 4]
```diff
@@ -141,6 +141,13 @@ const Select: React.FunctionComponent<React.PropsWithChildren<SelectProps>> = ({
     }
   }, [])
 
+  useEffect(() => {
+    if(defaultOptionIndex) {
```
Comment (chef-jojo) [inline src/components/Select/Select.tsx:145]:
```suggestion
    if (defaultOptionIndex) {
```

do you have prettier or any editor extension installed?
recommended to have a proper setup for formatting

File: src/components/Select/Select.tsx (hunk 3 above)
Comment (stvegerrad) [reply src/components/Select/Select.tsx:146]: If the index starts by 0, we can't detect first changes when the user sort the table using table header.
That's why I starts the index by 1.

Comment (stvegerrad) [reply src/components/Select/Select.tsx:146]:
```
<Text color={!optionSelected && placeHolderText ? 'text' : undefined}>
  {!optionSelected && placeHolderText ? placeHolderText : options[selectedOptionIndex].label}
</Text>
```
As you can see here, **select** component only shows the current sort field when optionSelected is false.
In case the user sort the table using table header, that value doesn't change.
I solved this problem by starting the index from 1.

File: src/components/Select/Select.tsx (hunk 4 above)
Comment (stvegerrad) [reply src/components/Select/Select.tsx]: fixed

**Comment by stvegerrad** [comment]
I think all issues are solved
Do you think so? @chef-jojo @memoyil

**Review by chef-jojo — APPROVED** [review]
Should refactor the select into accept value prop later.
Other than that should be good to go
Thanks for the pr
