### PR TITLE
fix: Get token pair link in farms, apr and staked sections

### LINKED ISSUE #677: Get token pair link that contains BNB opens liquidity page with WBNB
**Bug Description**
Get token pair link that contains BNB opens liquidty page with WBNB

**Steps to Reproduce**

1. Go to farms
2. Click on CAKE-BNB
3. Click Get CAKE-BNB LP
4. See it shows WBNB instead of BNB in liquidity page

**Expected Behavior**
It should select BNB

### LINKED ISSUE #696: Get token pair link in APY page shows BNB/BNB
**Bug Description**

Get token pair link in APY page shows BNB/BNB

**Steps to Reproduce**

1. Go to farms
2. Click on calculate button next to one of the farms apy
3. Check the link on the bottom
   

**Expected Behavior**
It should have the correct add liquidity link

### PR DESCRIPTION
**Pull request by memoyil**
Fixes #677
Fixes #696

### CODE REVIEW

File: src/utils/getLiquidityUrlPathParts.ts [hunk 1]
```diff
@@ -1,9 +1,15 @@
 // Constructing the two forward-slash-separated parts of the 'Add Liquidity' URL
 // Each part of the url represents a different side of the LP pair.
-const getLiquidityUrlPathParts = ({ quoteTokenAdresses, tokenAddresses }) => {
+import { getWbnbAddress } from './addressHelpers'
+
+const getLiquidityUrlPathParts = ({ quoteTokenAddress, tokenAddress }) => {
   const chainId = process.env.REACT_APP_CHAIN_ID
-  const firstPart = quoteTokenAdresses ? quoteTokenAdresses[chainId] : 'BNB'
-  const secondPart = tokenAddresses ? tokenAddresses[chainId] : 'BNB'
+  const wBNBAddressString = getWbnbAddress()
```
Comment (RabbitDoge) [inline src/utils/getLiquidityUrlPathParts.ts:7]: can you explain why this change is needed ?

Comment (memoyil) [reply src/utils/getLiquidityUrlPathParts.ts:7]: Because farm quote token contains wbnb address instead of null, that causes we still redirect user to (wbnb - token ) add liquidity page.

**Review by RabbitDoge — APPROVED** [review]
