### PR TITLE
fix: Black icon and texts in dark theme

### LINKED ISSUE #681: [Bug] some icons and font on some devices is black
**Bug Description**
While using trust wallet, there are some icons and font which are displaying as black on my device.

**Steps to Reproduce**
Unsure if reproducible
Visit https://pancakeswap.finance/pools on trust wallet ios 

**Expected Behavior**
The font and icon colour should match what displays on the desktop

**Additional Context**

### PR DESCRIPTION
**Pull request by memoyil**
Fixes #681

### CODE REVIEW

File: src/views/Pools/components/CardFooter.tsx [hunk 1]
```diff
@@ -105,12 +106,12 @@ const CardFooter: React.FC<Props> = ({
...
 
+  const { isDark } = useTheme()
+
   return (
     <StyledFooter isFinished={isFinished}>
       <Row>
-        <FlexFull>
-          <Tag />
-        </FlexFull>
+        <FlexFull>{Tag({ outline: !isDark })}</FlexFull>
```
Comment (hachiojidev) [inline src/views/Pools/components/CardFooter.tsx:114]: Why change to a function?

**Review by hachiojidev — CHANGES_REQUESTED** [review]

File: src/views/Pools/components/CardFooter.tsx (hunk 1 above)
Comment (memoyil) [reply src/views/Pools/components/CardFooter.tsx]: FIxed

**Review by memoyil — COMMENTED** [review]
Fixed in next commit

**Comment by memoyil** [comment]
@hachiojidev ready for you to review again

File: src/components/Balance.tsx [hunk 2]
```diff
@@ -16,7 +16,15 @@ interface BalanceProps extends TextProps {
 }
 
 const StyledText = styled(Text)<TextProps>`
-  color: ${({ isDisabled, color, theme }) => (isDisabled ? theme.colors.textDisabled : color)};
+  color: ${({ isDisabled, color, theme }) => {
+    if (isDisabled) {
+      return theme.colors.textDisabled
+    }
+    if (!color) {
```
Comment (RabbitDoge) [inline src/components/Balance.tsx:23]: 🤔 
```
   if (!color) {
      return color
    }
```

Comment (RabbitDoge) [reply src/components/Balance.tsx:23]: this change doesn't seem useful because the color already default to `text`

File: src/components/Tags.tsx [hunk 3]
```diff
@@ -1,28 +1,41 @@
...
-  <Tag variant="secondary" outline startIcon={<VerifiedIcon />} {...props}>
-    Core
-  </Tag>
-)
+const CoreTag = (props) => {
+  const { isDark } = useTheme()
+  return (
+    <Tag variant="secondary" outline={!isDark} startIcon={<VerifiedIcon />} {...props}>
+      Core
+    </Tag>
```
Comment (hachiojidev) [inline src/components/Tags.tsx:10]: I think these are suppose to remain solid. If this is just to fix the icon color you can apply the color to the icon directly.

```
<Tag variant="secondary" outline startIcon={<VerifiedIcon color="secondary" />} {...props}>
```

Comment (memoyil) [reply src/components/Tags.tsx]: Done

File: src/components/Balance.tsx (hunk 2 above)
Comment (memoyil) [reply src/components/Balance.tsx]: You are right, don't remember why i put it there :D. I changed now, i am checking against default color value if there is no value coming from component props (which in this case) I fallback to theme text color .

**Comment by memoyil** [comment]
@hachiojidev @RabbitDoge You can review it again

File: src/components/Balance.tsx (hunk 2 above)
Comment (RabbitDoge) [reply src/components/Balance.tsx]: For me, this change does exactly the same thing than the code before, but with more code. I'm not sure I understand what you're trying to do

Comment (memoyil) [reply src/components/Balance.tsx]: Issue is when you switch to dark theme, it uses the same color value which is ‘text’ instead of theme one  unless it is passed explicitly. Thats why I added a theme.color.text. It is reproducible in iOS.

Comment (RabbitDoge) [reply src/components/Balance.tsx]: `text` and `theme.color.text` are the same

File: src/components/Balance.tsx [hunk 4]
```diff
@@ -16,7 +16,15 @@ interface BalanceProps extends TextProps {
...
-  color: ${({ isDisabled, color, theme }) => (isDisabled ? theme.colors.textDisabled : color)};
+  color: ${({ isDisabled, color, theme }) => {
+    if (isDisabled) {
+      return theme.colors.textDisabled
+    }
+    if (color !== Balance.defaultProps.color) {
+      return color
+    }
+    return theme.colors.text
+  }};
```
Comment (dobpp) [inline src/components/Balance.tsx:27]: color: ${({ isDisabled, color, theme }) => isDisabled ? theme.colors.textDisabled : color !== Balance.defaultProps.color ? color : theme.color.text}};

Comment (memoyil) [reply src/components/Balance.tsx:27]: I think nested ternary conditions is not readable simply

File: src/components/Balance.tsx (hunk 2 above)
Comment (memoyil) [reply src/components/Balance.tsx]: Good news, I think i found the issue, when we use styledtext with css attributes, it overrides color attribute of actual dom object and interpreted as color: 'text' or color: 'textdisabled' instead of actual html color values. Browsers failed and fallback to other color and in some browsers (metamask, safari) it is different than we expect. Thats why I removed styledText and put condition in Text props.

File: src/components/Balance.tsx (hunk 4 above)
Comment (RabbitDoge) [reply src/components/Balance.tsx]: Nested ternaries raise an error with our eslint config

**Review by RabbitDoge — APPROVED** [review]

**Review by hachiojidev — APPROVED** [review]
