### PR TITLE
fix: No 'approve' state on the dashboard lottery modal. Fixes #310

### LINKED ISSUE #310: No 'approve' state on the dashboard lottery modal.
https://user-images.githubusercontent.com/71833681/104863019-2fede700-5978-11eb-9459-0d1abc037832.mov

**Bug Description**
On the dashboard there is no approve state, so a user is unable to approve contract interaction and when clicking "buy tickets" they are unable to buy tickets. 

**Steps to Reproduce**

1. Go to dashboard on a new wallet
2. Click on buy tickets
  
**Expected Behavior**
Buy tickets would not show, the approve button should.

### PR DESCRIPTION
**Pull request by karelianpie**
Fixes https://github.com/pancakeswap/pancake-frontend/issues/310

Adds the approve state so that the"Approve" button is shown instead of the "Buy tickets". I've duplicated the logic of `src/views/Lottery/components/TicketCard/TicketActions.tsx` as I'm not yet too familiar with the codebase.

### CODE REVIEW

File: src/views/Home/components/LotteryCard.tsx [hunk 1]
```diff
@@ -44,10 +47,28 @@ const FarmedStakingCard = () => {
...
   const TranslateString = useI18n()
+  const allowance = useLotteryAllowance()
+  const { onApprove } = useLotteryApprove()
+  const [onPresentApprove] = useModal(<PurchaseWarningModal />)
+  const [requestedApproval, setRequestedApproval] = useState(false)
   const { claimAmount } = useTotalClaim()
   const { onMultiClaim } = useMultiClaimLottery()
   const cakeBalance = useTokenBalance(getCakeAddress())
 
+  const handleApprove = useCallback(async () => {
```
Comment (RabbitDoge) [inline src/views/Home/components/LotteryCard.tsx:58]: the whole code here has been copied from `TicketActions.tsx`. Please create a hook in order to avoid duplicate code.

**Review by RabbitDoge — CHANGES_REQUESTED** [review]

File: src/views/Home/components/LotteryCard.tsx (hunk 1 above)
Comment (karelianpie) [reply src/views/Home/components/LotteryCard.tsx]: @RabbitDoge, I've refactored that code to a new hook with https://github.com/pancakeswap/pancake-frontend/pull/423/commits/f96f74d29e34eef3f82d80035ad2ac6b2f1e039c

As I'm unfamiliar with the best practices in this codebase, please let me know about naming conventions and where to put the hook itself. As it's used by two sibling views I've placed it in the `src/hooks`.

**Review by RabbitDoge — APPROVED** [review]
