### PR TITLE
fix: Page title shows "false" when loading

### LINKED ISSUE #794: Page title shows "false" when price is loading
Screenshot 2021-04-05 at 14 04 34

### PR DESCRIPTION
**Pull request by memoyil**
Fixes #794

### CODE REVIEW

File: src/components/layout/Page.tsx [hunk 1]
```diff
@@ -25,19 +25,19 @@ const StyledPage = styled(Container)`
...
+  const cakePriceUsdDisplay = cakePriceUsd.eq(0)
+    ? ''
+    : `$${cakePriceUsd.toNumber().toLocaleString(undefined, {
+        minimumFractionDigits: 3,
+        maximumFractionDigits: 3,
+      })}`
   const pageMeta = customMeta[pathname] || {}
   const { title, description, image } = { ...DEFAULT_META, ...pageMeta }
-  const titleWithPrice = [title, cakePriceUsdDisplay].join(' - ')
+  const pageTitle = cakePriceUsdDisplay ? [title, cakePriceUsdDisplay].join(' - ') : title
```
Comment (Chef-Cheems) [inline src/components/layout/Page.tsx:36]: Was going to comment that we could just keep the original `cakePriceUsdDisplay` (with `gt(0) && ...`) and change only this line (36). But then figured out that with this change `cakePriceUsdDisplay` would be nice `string` type instead of `bool | string` 👍

**Review by Chef-Cheems — APPROVED** [review]
LGTM

**Review by hachiojidev — APPROVED** [review]
