### PR TITLE
fix: Missing margin lottery won card

### LINKED ISSUE #869: Lottery Won Card doesn't have margin
**Android:**

**Ipad:**

**Iphone:**

**Desktop:**

### PR DESCRIPTION
**Pull request by memoyil**
Fixes #869 

**Ipad:**

**Android:**

**Iphone:**

**Desktop:**

### CODE REVIEW

File: src/views/Lottery/components/YourPrizesCard/index.tsx [hunk 1]
```diff
@@ -7,21 +7,24 @@ import PrizesWonContent from './PrizesWonContent'
 import NoPrizesContent from './NoPrizesContent'
 
 const StyledCard = styled(Card)`
+  margin-top: 16px;
+
+  ${(props) => `
```
Comment (hachiojidev) [inline src/views/Lottery/components/YourPrizesCard/index.tsx:12]: Wrapping this in a function with props is not necessary. This is the pattern we use around the site.

```
${({ theme }) => theme.mediaQueries.sm} {

}
```

**Review by hachiojidev — CHANGES_REQUESTED** [review]

File: src/views/Lottery/components/YourPrizesCard/index.tsx (hunk 1 above)
Comment (memoyil) [reply src/views/Lottery/components/YourPrizesCard/index.tsx]: done

**Review by hachiojidev — APPROVED** [review]
