### PR TITLE
fix(swap): Switch token onclick and icon

### LINKED ISSUE #2854: Button for switching currency pair not working properly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

Pressing the button to switch the currency pair (i.e the button that changes bnb/busd to busd/bnb) around does not work properly. This only works when specifically pressing the arrow within the button and not the edges of the button. 

### Expected Behavior

Pressing the button to swap currencies around should swap the currencies.

### Steps To Reproduce

1. Open any browser
2. Go to [https://pancakeswap.finance/swap](https://pancakeswap.finance/swap)
3. Click not in the center of the button which switches the currency pair around. (clicking out of the hitbox for the arrow)

### Environment

```markdown
- Device: N/A 
- OS: N/A
- Browser: Any desktop browser
- Wallet: N/A
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chef-jojo**
Fix #2854 and update swap icon

### CODE REVIEW

File: src/views/Swap/index.tsx [hunk 1]
```diff
@@ -68,6 +70,32 @@ const Label = styled(Text)`
...
+      fill: white;
+    }
+    .icon-up-down {
+      display: block;
+      fill: white;
+    }
+  }
+`
+
+const ArrowUpDownIcon: React.FC<SvgProps> = (props) => {
```
Comment (chef-jojo) [inline src/views/Swap/index.tsx:91]: will move this to uikit https://github.com/pancakeswap/pancake-toolkit/pull/350/files

**Review by Chef-Cheems — APPROVED** [review]
