### PR TITLE
fix(priceDecimal): Handle prices lower than 3 decimal

### LINKED ISSUE #2029: Show `<$0.001` when lock price and close price difference is less than 0.001

### PR DESCRIPTION
**Pull request by 0xCorgi**
Fix #2029

[Live version](https://endurable-yam.surge.sh/prediction)

Prices that are below `0.001` are now displayed with `<0.001`.

### CODE REVIEW

**Review by ChefHutch — COMMENTED** [review]
Noice! And look at those tests 😍 

Just a few nitpicky things but good stuff

File: src/views/Predictions/helpers.ts [hunk 1]
```diff
@@ -1,15 +1,36 @@
...
+  let prefix = unitPrefix
+  let priceToFormat = value
+  const sign = value.isNegative() ? BigNumber.from(-1) : BigNumber.from(1)
+
+  if (value.abs().lt(minPriceDisplayed)) {
+    prefix = `<${unitPrefix}`
+    priceToFormat = minPriceDisplayed.mul(sign)
+  }
+
+  return `${prefix}${formatBigNumberToFixed(priceToFormat, 3, displayDecimals)}`
```
[the remark this answers is not in the document]
Comment (0xCorgi) [reply src/views/Predictions/helpers.ts:25]: You're right, I'll fix thix.

File: src/views/Predictions/helpers.ts [hunk 2]
```diff
@@ -1,15 +1,36 @@
-import { ethers } from 'ethers'
+import { BigNumber, ethers } from 'ethers'
 import { NodeRound } from 'state/types'
 import { formatBigNumberToFixed } from 'utils/formatBalance'
 import getTimePeriods from 'utils/getTimePeriods'
 
+const MIN_PRICE_USD_DISPLAYED = BigNumber.from(100000)
+const MIN_PRICE_BNB_DISPLAYED = BigNumber.from('1000000000000000')
```
[the remark this answers is not in the document]
Comment (0xCorgi) [reply src/views/Predictions/helpers.ts:7]: Yes, the second call to `BigNumber.from` was breaking with a plain number.

File: src/views/Predictions/helpers.ts [hunk 3]
```diff
@@ -1,15 +1,44 @@
...
+  decimals: number
+}
+
+const formatPriceDifference = ({
+  price = BigNumber.from(0),
+  minPriceDisplayed,
+  unitPrefix,
+  decimals,
+}: formatPriceDifferenceProps) => {
+  const value = price
```
Comment (hachiojidev) [inline src/views/Predictions/helpers.ts:23]: Any reason to instantiate this variable and not use `price` directly?

File: src/views/Predictions/helpers.ts [hunk 4]
```diff
@@ -1,15 +1,44 @@
...
+  let prefix = unitPrefix
+  let priceToFormat = value
+  const sign = value.isNegative() ? BigNumber.from(-1) : BigNumber.from(1)
+
+  if (value.abs().lt(minPriceDisplayed)) {
+    prefix = `<${unitPrefix}`
+    priceToFormat = minPriceDisplayed.mul(sign)
+  }
```
Comment (hachiojidev) [inline src/views/Predictions/helpers.ts:31]: Totally valid code but try and avoid using `let` and return ``<${unitPrefix}`` early.

File: src/views/Predictions/helpers.test.ts [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+    ${'-100000000000000'}       | ${'<-0.001'}
+    ${'-10000000000000'}        | ${'<-0.001'}
+    ${'-1000000000000'}         | ${'<-0.001'}
+    ${'-100000000000'}          | ${'<-0.001'}
+  `(
+    'should format $priceDifference to $expectedPriceDifferenceFormatted',
+    ({ priceDifference, expectedPriceDifferenceFormatted }) =>
+      expect(formatBnbv2(BigNumber.from(priceDifference))).toEqual(expectedPriceDifferenceFormatted),
+  )
+})
```
Comment (hachiojidev) [inline src/views/Predictions/helpers.test.ts:61]: I wholeheartedly agree to put tests next to the file. We just have to convince @RabbitDoge who seems to be the straggler. So for now can you put it in the `src/__test__/views/Predictions/helpers.test.ts`

**Review by hachiojidev — CHANGES_REQUESTED** [review]
Nice work dude.

File: src/views/Predictions/helpers.ts (hunk 3 above)
Comment (0xCorgi) [reply src/views/Predictions/helpers.ts:23]: Good point, it was used for doing a default assignment before. Since it's done in the params now I will clean this.

File: src/views/Predictions/helpers.ts (hunk 4 above)
Comment (0xCorgi) [reply src/views/Predictions/helpers.ts:31]: I also like to avoid `let` as much as possible, just wanted to mutualize the condition here.
I will use an early return instead.

**Review by hachiojidev — APPROVED** [review]
