### PR TITLE
fix: Apr shows loading in finished farms

### LINKED ISSUE #738: Finished farms apr shows loading
**Bug Description**
Finished farms apr shows loading

**Steps to Reproduce**

1. Go to farms
2. Click on finished
3. Check apr

**Expected Behavior**
It should show 0

### PR DESCRIPTION
**Pull request by memoyil**
Fixes #738

### CODE REVIEW

File: src/views/Farms/Farms.tsx [hunk 1]
```diff
@@ -170,31 +171,26 @@ const Farms: React.FC = () => {
...
 
       if (query) {
         const lowercaseQuery = query.toLowerCase()
         farmsToDisplayWithAPY = farmsToDisplayWithAPY.filter((farm: FarmWithStakedValue) => {
-          if (farm.lpSymbol.toLowerCase().includes(lowercaseQuery)) {
-            return true
-          }
-
-          return false
+          return farm.lpSymbol.toLowerCase().includes(lowercaseQuery)
```
Comment (RabbitDoge) [inline src/views/Farms/Farms.tsx:182]: hahaha nice catch

**Review by RabbitDoge — APPROVED** [review]
