### PR TITLE
fix: (create-profile): Username availability check hangs intermittently

### LINKED ISSUE #2558: always staying at confirming "set your name"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

always staying at confirming "set your name" more than for 12 hours 

### Expected Behavior

success to confirm and complete profile activation 

### Steps To Reproduce

setup profile 

### Environment

```markdown
- Device: 
- OS: 
- Browser:
- Wallet:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by memoyil**
To review:

https://deploy-preview-2623--pancakeswap-dev.netlify.app/

Fixes #2558

It ensures that debounced fetch requests are in order (abort when new request comes if previous still fetching) and fetch request itself has timeout

### CODE REVIEW

File: src/views/ProfileCreation/UserName.tsx [hunk 1]
```diff
@@ -81,28 +83,56 @@ const UserName: React.FC = () => {
...
+        setIsLoading(true)
+        if (!debouncedUsernameAvailability) {
+          setIsValid(false)
+          setMessage('')
+          fetchAbortSignal.current = null
+        } else {
+          const res = (await fetchWithTimeout(`${API_PROFILE}/api/users/valid/${debouncedUsernameAvailability}`, {
+            method: 'get',
+            signal: abortSignal,
+            timeout: 30000,
```
Comment (memoyil) [inline src/views/ProfileCreation/UserName.tsx:101]: 30 seconds enough to fetch data I think

File: src/utils/fetchWithTimeout.ts [hunk 2]
```diff
@@ -0,0 +1,15 @@
+const fetchWithTimeout = (url, options = {}) => {
```
Comment (Chef-Cheems) [inline src/utils/fetchWithTimeout.ts:1]: `options` can be typed as RequestInit perhaps? Then `// @ts-ignore` can be removed

File: src/views/ProfileCreation/UserName.tsx [hunk 3]
```diff
@@ -81,28 +83,56 @@ const UserName: React.FC = () => {
   )
   const isUserCreated = existingUserState === ExistingUserState.CREATED
 
-  const checkUsernameValidity = debounce(async (value: string) => {
-    try {
-      setIsLoading(true)
-      const res = await fetch(`${API_PROFILE}/api/users/valid/${value}`)
+  const [usernameAvailability, setUsernameAvailability] = useState<string>(undefined)
```
Comment (Chef-Cheems) [inline src/views/ProfileCreation/UserName.tsx:86]: `usernameAvailability` is basically just the string typed by user? Should probably rename to something less ambiguous, like "username" or "usernameToCheck". 🤔

File: src/views/ProfileCreation/UserName.tsx [hunk 4]
```diff
@@ -81,28 +83,56 @@ const UserName: React.FC = () => {
...
+        if (!debouncedUsernameAvailability) {
+          setIsValid(false)
+          setMessage('')
+          fetchAbortSignal.current = null
+        } else {
+          const res = (await fetchWithTimeout(`${API_PROFILE}/api/users/valid/${debouncedUsernameAvailability}`, {
+            method: 'get',
+            signal: abortSignal,
+            timeout: 30000,
+          })) as Response
```
Comment (Chef-Cheems) [inline src/views/ProfileCreation/UserName.tsx:102]: Response type can be typed in `fetchWithTimeout` as `Promise<Response>`.

File: src/views/ProfileCreation/UserName.tsx [hunk 5]
```diff
@@ -81,28 +83,56 @@ const UserName: React.FC = () => {
...
+      } finally {
+        setIsLoading(false)
       }
-    } finally {
-      setIsLoading(false)
     }
-  }, 200)
+
+    if (fetchAbortSignal.current) {
+      fetchAbortSignal.current.abort()
```
Comment (Chef-Cheems) [inline src/views/ProfileCreation/UserName.tsx:124]: hm... when you `.abort()` the request that request gets rejected with AbortError. I wonder if that would make an error message appear for a short time. 🤔 
Have you tested it somehow during the request cancellation? I know it might be tricky but worth taking a look 👀

File: src/utils/fetchWithTimeout.ts (hunk 2 above)
Comment (memoyil) [reply src/utils/fetchWithTimeout.ts]: Done

File: src/views/ProfileCreation/UserName.tsx (hunk 3 above)
Comment (memoyil) [reply src/views/ProfileCreation/UserName.tsx]: Done

File: src/views/ProfileCreation/UserName.tsx (hunk 4 above)
Comment (memoyil) [reply src/views/ProfileCreation/UserName.tsx]: Done

File: src/views/ProfileCreation/UserName.tsx (hunk 5 above)
Comment (memoyil) [reply src/views/ProfileCreation/UserName.tsx:126]: Correct, I added a check for that

**Comment by yonger1516** [comment]
hurry up. thanks for your work.

**Comment by yonger1516** [comment]
mising ifo.....

**Review by Chef-Cheems — APPROVED** [review]

**Comment by Chef-Cheems** [comment]
@yonger1516 agh, sorry, didn't have time to look carefully at it :( Hope you got in before IFO 🙈

**Comment by yonger1516** [comment]
you're welcome.  when the fixed code will be released online ?

**Comment by yonger1516** [comment]
@Chef-Cheems .  when the fixed code will be released online ?

**Comment by memoyil** [comment]
@yonger1516 It is online, you still had the issue?

**Comment by yonger1516** [comment]
@memoyil  yes, the issue persist.
